### ISSUE TITLE
Dev Environment: Node Install (Repo)

### ISSUE THREAD

**Issue by douglassims** [ProjectMeniscus/meniscus#175]
## Acceptance Criteria
- Node install
### Tasks:
- [x]  Set up repo @aelkikhia
- [x]  configure process @chadlung 
- [ ] Write Tests 
- [ ] Document on wiki
